spring:
  data:
    mongodb:
      uri: mongodb://user:user@165.22.74.235:27017/scrappers
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2
