spring:
  data:
    mongodb:
      uri: ${mongo_uri}
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${h2_username}
    password: ${h2_password}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2
