name: Check if builds on push

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml
